package javaapplication1;

import java.net.*;
import java.io.*;

public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        verify1Servlet = new javax.swing.JButton();
        verify2JSP = new javax.swing.JButton();
        IDTextField = new javax.swing.JTextField();
        JSPPasswordTextField = new javax.swing.JTextField();
        urlNoteTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        getSystemDataButton = new javax.swing.JButton();
        getUDPTableButton = new javax.swing.JButton();
        getTCPTableButton = new javax.swing.JButton();
        getARPTableButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        servletPasswordTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 156, 209));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 156, 209));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");
        jLabel3.setToolTipText("");

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        verify1Servlet.setBackground(new java.awt.Color(255, 156, 209));
        verify1Servlet.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        verify1Servlet.setText("Verify 1");
        verify1Servlet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verify1Servlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify1ServletActionPerformed(evt);
            }
        });

        verify2JSP.setBackground(new java.awt.Color(255, 156, 209));
        verify2JSP.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        verify2JSP.setText("Verify 2");
        verify2JSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verify2JSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify2JSPActionPerformed(evt);
            }
        });

        IDTextField.setBackground(new java.awt.Color(255, 156, 209));
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        JSPPasswordTextField.setBackground(new java.awt.Color(255, 156, 209));
        JSPPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSPPasswordTextFieldActionPerformed(evt);
            }
        });

        urlNoteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlNoteTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Notes");

        getSystemDataButton.setBackground(new java.awt.Color(255, 156, 209));
        getSystemDataButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getSystemDataButton.setText("Get System Data");
        getSystemDataButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getSystemDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSystemDataButtonActionPerformed(evt);
            }
        });

        getUDPTableButton.setBackground(new java.awt.Color(255, 156, 209));
        getUDPTableButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getUDPTableButton.setText("UDP Table");
        getUDPTableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getUDPTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUDPTableButtonActionPerformed(evt);
            }
        });

        getTCPTableButton.setBackground(new java.awt.Color(255, 156, 209));
        getTCPTableButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getTCPTableButton.setText("TCP Table");
        getTCPTableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getTCPTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTCPTableButtonActionPerformed(evt);
            }
        });

        getARPTableButton.setBackground(new java.awt.Color(255, 156, 209));
        getARPTableButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getARPTableButton.setText("ARP Table");
        getARPTableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getARPTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getARPTableButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 156, 209));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PASSWORD");
        jLabel5.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(255, 156, 209));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Name");
        jLabel6.setToolTipText("");

        NameTextField.setBackground(new java.awt.Color(255, 156, 209));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        servletPasswordTextField.setBackground(new java.awt.Color(255, 156, 209));
        servletPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servletPasswordTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 156, 209));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("JSP");
        jLabel7.setToolTipText("");

        jLabel8.setBackground(new java.awt.Color(255, 156, 209));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Servlet");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(urlNoteTextField)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(getSystemDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(getUDPTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(getTCPTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getARPTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verify1Servlet, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verify2JSP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(servletPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(NameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(JSPPasswordTextField))
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JSPPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(servletPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verify1Servlet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verify2JSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getTCPTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(getSystemDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getUDPTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getARPTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlNoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verify1ServletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify1ServletActionPerformed
        // TODO add your handling code here: GET
        servlet_auth();

    }//GEN-LAST:event_verify1ServletActionPerformed

    private void verify2JSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify2JSPActionPerformed
        jsp_auth();

    }//GEN-LAST:event_verify2JSPActionPerformed

    private void JSPPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSPPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JSPPasswordTextFieldActionPerformed

    private void getSystemDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSystemDataButtonActionPerformed
        // TODO add your handling code here: 
        int b;
        if (response1.trim().equals(response2.trim()) && response1.trim().equals("Permit")) {

            new SystemGroup().setVisible(true);
            this.toBack();

        } else {
            System.out.println("Check Your Credentials");
        }

    }//GEN-LAST:event_getSystemDataButtonActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void urlNoteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlNoteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlNoteTextFieldActionPerformed

    private void getUDPTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUDPTableButtonActionPerformed
        // TODO add your handling code here:
        int b;
        if (response1.trim().equals(response2.trim()) && response1.trim().equals("Permit")) {

            new UDPTable().setVisible(true);
            this.toBack();

        } else {
            System.out.println("Check Your Credentials");
        }
    }//GEN-LAST:event_getUDPTableButtonActionPerformed

    private void getTCPTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTCPTableButtonActionPerformed
        // TODO add your handling code here:
        int b;
        if (response1.trim().equals(response2.trim()) && response1.trim().equals("Permit")) {

            new TCPTable().setVisible(true);
            this.toBack();

        } else {
            System.out.println("Check Your Credentials");
        }
    }//GEN-LAST:event_getTCPTableButtonActionPerformed

    private void getARPTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getARPTableButtonActionPerformed
        // TODO add your handling code here:
        int b;
        if (response1.trim().equals(response2.trim()) && response1.trim().equals("Permit")) {

            new ARPTable().setVisible(true);
            this.toBack();

        } else {
            System.out.println("Check Your Credentials");
        }
    }//GEN-LAST:event_getARPTableButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void servletPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servletPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servletPasswordTextFieldActionPerformed

    String contentStr = "application/x-www-form-urlencoded";
    String response1 = "";
    String response2 = "";

    void jsp_auth() {
        String ID = this.IDTextField.getText();
        String pass = this.JSPPasswordTextField.getText();
        try {
            String string = "http://localhost:8080/hello/auth.jsp" + "?ID=" + ID + "&password=" + pass;
            URL url = new URL(string);               //+"?"+dataStr
            this.urlNoteTextField.setText("JSP: " + string);
            int b;
            StringBuilder response = new StringBuilder();
            HttpURLConnection myConn = (HttpURLConnection) url.openConnection();
            InputStream inputStream = myConn.getInputStream();
            while ((b = inputStream.read()) != -1) {
                response.append((char) b);
            }
            this.outputArea.setText(response.toString());
            response2 = response.toString();

        } catch (Exception e) {
            System.out.println(e.toString());
            this.outputArea.setText("Failed: Exception");
        }

    }

    void servlet_auth() {
        String Name = this.NameTextField.getText();
        String pass = this.servletPasswordTextField.getText();
        try {
            String string = "http://localhost:8080/hello/auth" + "?Name=" + Name + "&password=" + pass;
            URL url = new URL(string);               //+"?"+dataStr
            this.urlNoteTextField.setText("Servlet: sending to " + string);
            int b;
            StringBuilder response = new StringBuilder();
            HttpURLConnection myConn = (HttpURLConnection) url.openConnection();
            InputStream is = myConn.getInputStream();
            while ((b = is.read()) != -1) {
                response.append((char) b);
            }
            this.outputArea.setText(response.toString());
            response1 = response.toString();

        } catch (Exception e) {
            System.out.println(e);
            this.outputArea.setText("Failed: Exception");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField JSPPasswordTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton getARPTableButton;
    private javax.swing.JButton getSystemDataButton;
    private javax.swing.JButton getTCPTableButton;
    private javax.swing.JButton getUDPTableButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JTextField servletPasswordTextField;
    private javax.swing.JTextField urlNoteTextField;
    private javax.swing.JButton verify1Servlet;
    private javax.swing.JButton verify2JSP;
    // End of variables declaration//GEN-END:variables
}
